server:
  port: 8081

spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/identity_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true