version: '3.8'

services:
  identity-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: identity-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/identity_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - postgres
      - kafka
    networks:
      - e-commerce-network

  postgres:
    image: postgres:16-alpine
    container_name: identity-postgres
    environment:
      POSTGRES_DB: identity_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - e-commerce-network

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: identity-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - e-commerce-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: identity-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - e-commerce-network

volumes:
  postgres-data:

networks:
  e-commerce-network:
    driver: bridge
